### PR TITLE
coverting matlab labs to python

### PR DESCRIPTION
**Pull request by orel509**
complete conversion of matlab labs to python. tested and got same outputs as in matlab.

### CODE REVIEW

**Comment by royhershkovitz** [comment]
hello Orel,

Good job so far.

We want the files as google Colab applicable files - .ipynb format.
This format enables you to run the code segments on the web browser add description blocks and be organized.

here is an example of fetching the traces and displaying using Bokeh graphs
https://colab.research.google.com/github/Yossioren/AttacksonImplementationsCourseBook/blob/master/Labs/Lecture3.ipynb

Can you convert your files to .ipynb and make sure it displays correctly on Colab?

**Comment by orel509** [comment]
I can give it a try, but I never worked before ipynb format or google Colab, so I'm not sure I will be able to make it look exactly like you expect it to look. is that OK?

**Comment by royhershkovitz** [comment]
hello,

I think it quite easy,
**So I will give a short explanation:**
You have a blocks of code and blocks of text you can decide what order they will be.
You can define functions and exec them as regular python.

You can think of the whole thing as running multiple commands blocks on **one session of python shell** - 
When you run one block the functions and global parameters are saved in the environment so you can run one block of commands to get the data, view the results and then continue to run the block of the algorithm, in between you can add blocks of explanation instead of comments.

For fast warmup you have the example Yossi had created, it will run in the collab, you can see how to get the data and plot.
I checked and the .ipynb had nice support in VS-CODE this is **a nice and short tutorial** I have found https://youtu.be/_C0vbLV6WdA?t=61 few minutes will explain to you most (and more) of what I have written.


lastly, it is important for Dr. Oren and it had a lot of advantages.
I am here to help, and sure you will figure it out easily.

**Comment by orel509** [comment]
I added the labs in ipynb format, created in google colab, as required.

**Comment by royhershkovitz** [comment]
good job so far guys, I had made it works on Colab. And I will check the outputs

**Comment by royhershkovitz** [comment]
Hello, good job so far!

With matplotlib, the graphs are too small, and we can't zoom.
We need to move to a tool call bokeh and it far more interactive. like presented in the demo.
I already turned most of the graphs to bokeh. The expectation is that all the graphs will be presented via the Bokeh tool. If you will check out some of the graphs you will see how much difference this graph tool makes.

what left:
-  need to turn the images to bokeh images: https://docs.bokeh.org/en/latest/docs/gallery/image.html
- change all the 'TODO' with correct information so other people can understand what the graph shows
- turn correctly the second graph from the end of lecture 7

**Comment by royhershkovitz** [comment]
https://colab.research.google.com/github/orel509/AttacksonImplementationsCourseBook/blob/master/Labs/Lecture3.ipynb
https://colab.research.google.com/github/orel509/AttacksonImplementationsCourseBook/blob/master/Labs/Lecture5.ipynb
https://colab.research.google.com/github/orel509/AttacksonImplementationsCourseBook/blob/master/Labs/Lecture7.ipynb

**Comment by royhershkovitz** [comment]
Hello Orel,

I have a question-
When I try the DPA approach in lecture 7 the correct_time is always 0.
And it results in all the graphs afterward to not work.
Is this is the right behavior?
you can see it here, run all the blocks and change the second block to DPA
https://colab.research.google.com/github/orel509/AttacksonImplementationsCourseBook/blob/master/Labs/Lecture7.ipynb

**Pull request merged**
