### PR TITLE
07 High Data Complexity 1 formulas and figures updated

### PR DESCRIPTION
**Pull request by lionj97**
clarified what certain terms are, with nice and short explanations. added some pictures in order to explain these things as well. 
re-arranged some of the pictures in the chapter to more ideal locations as well.
wasn't 100% sure what else should be done.
thanks

### CODE REVIEW

**Comment by royhershkovitz** [comment]
hello, what is your name? (if you want, you can email me your name instead of posting here)
also, are you part of group 7 in the spreadsheet?

**Comment by lionj97** [comment]
Hi Roy,
My name is Ari Adler. Yes I am part of group 7 on the spreadsheet. Sorry
for the inconvenience.
Thanks!

Ari Adler

**Comment by royhershkovitz** [comment]
hello you forgot to commit images/Lecture6/HammingWeightBinary.png
can you pull the changes and add the missing file?

**Comment by royhershkovitz** [comment]
right now the image is commented on lines 39-43 of 07_High_Data_Complexity_Power_EM_1.tex

**Comment by lionj97** [comment]
created new pull request with required photo :)

**Pull request merged**
