### PR TITLE
Rearranged the Lecture Videos in an order

### PR DESCRIPTION
**Pull request by Lojenaa**
Video Links have fixed according to the title in an order

### CODE REVIEW

**Review by Yossioren — CHANGES_REQUESTED** [review]
Hi Lojenaa, the videos up to line 52 point to the playlist (have a playlist in the URL). Can you make the other videos (lines 54-150) point to the playlist as well?

**Comment by Lojenaa** [comment]
> Hi Lojenaa, the videos up to line 52 point to the playlist (have a playlist in the URL). Can you make the other videos (lines 54-150) point to the playlist as well?

Hi Yossi, Some of the videos are already point the correct links therefore, I haven't point it to the playlist. I will make it to the playlist and commit again.

**Comment by Lojenaa** [comment]
Hi Yossi,
All of the videos are now pointing to the playlist. Please verify!

**Comment by Yossioren** [comment]
Thanks

**Pull request merged**
